# Generated by Django 3.0.7 on 2020-08-11 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instituicao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('sobre', models.TextField(verbose_name='Sobre')),
                ('missao', models.TextField(verbose_name='Missão')),
                ('visao', models.TextField(verbose_name='Visão')),
                ('endereco', models.CharField(max_length=100, verbose_name='Endereço')),
                ('email', models.CharField(max_length=100, verbose_name='E-mail')),
                ('facebook', models.CharField(blank=True, max_length=255, null=True, verbose_name='Link Facebook')),
                ('instagram', models.CharField(blank=True, max_length=255, null=True, verbose_name='Link Instagram')),
                ('email_agendamento', models.CharField(max_length=100, verbose_name='E-mail para envio de Agendamento')),
                ('email_faleconosco', models.CharField(max_length=100, verbose_name='E-mail para envio de Fale Conosco')),
                ('telefone', models.CharField(max_length=100, verbose_name='Telefone')),
                ('patrono', models.TextField(verbose_name='Informações sobre Patrono')),
                ('atividade', models.TextField(verbose_name='Atividade')),
                ('policia_acervo', models.TextField(verbose_name='Políticas de Acervo')),
                ('periodos_visita', models.CharField(help_text='Exemplo: Manhã (das 09h às 12h);Tarde (das 14h às 17h)', max_length=255, verbose_name='Período de Visita (Separados por vírgula)')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Instituição e Site',
                'verbose_name_plural': 'Instituição e Site',
                'ordering': ['criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Membro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('funcao', models.CharField(max_length=100, verbose_name='Função')),
                ('imagem', models.ImageField(upload_to='', verbose_name='Foto do Membro da Equipe')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('instituicao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='membros', to='instituicao.Instituicao', verbose_name='Instituição')),
            ],
            options={
                'verbose_name': 'Membro da Equipe',
                'verbose_name_plural': 'Membros da Equipe',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='FotoInstituicao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='', verbose_name='Imagem da Instituição')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('instituicao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fotos', to='instituicao.Instituicao', verbose_name='Instituição')),
            ],
            options={
                'verbose_name': 'Foto da Instituição/Site',
                'verbose_name_plural': 'Fotos da Instituição/Site',
                'ordering': ['criado_em'],
            },
        ),
    ]
