# Generated by Django 3.0.5 on 2020-06-04 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instituicao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('sobre', models.TextField(verbose_name='Sobre')),
                ('missao', models.TextField(verbose_name='Missão')),
                ('visao', models.TextField(verbose_name='Visão')),
                ('endereco', models.TextField(verbose_name='Endereço')),
                ('email', models.TextField(verbose_name='E-mail')),
                ('email_agendamento', models.TextField(verbose_name='E-mail para envio de Agendamento')),
                ('telefone', models.TextField(verbose_name='Telefone')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Instituição e Site',
                'verbose_name_plural': 'Instituição e Site',
                'ordering': ['criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Membro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('funcao', models.TextField(verbose_name='Função')),
                ('image', models.ImageField(upload_to='', verbose_name='Foto do Membro da Equipe')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('instituicao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='membros', to='instituicao.Instituicao', verbose_name='Instituição')),
            ],
            options={
                'verbose_name': 'Membro da Equipe',
                'verbose_name_plural': 'Membros da Equipe',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='FotoInstituicao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posicao', models.TextField(verbose_name='Posição')),
                ('imagem', models.ImageField(upload_to='', verbose_name='Imagem da Instituição')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('instituicao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fotos', to='instituicao.Instituicao', verbose_name='Instituição')),
            ],
            options={
                'verbose_name': 'Foto da Instituição/Site',
                'verbose_name_plural': 'Fotos da Instituição/Site',
                'ordering': ['criado_em'],
            },
        ),
    ]
