# Generated by Django 3.0.7 on 2020-11-19 17:12

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instituicao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instituicao',
            name='atividade',
            field=ckeditor.fields.RichTextField(verbose_name='Atividade'),
        ),
        migrations.AlterField(
            model_name='instituicao',
            name='missao',
            field=ckeditor.fields.RichTextField(verbose_name='Missão'),
        ),
        migrations.AlterField(
            model_name='instituicao',
            name='patrono',
            field=ckeditor.fields.RichTextField(verbose_name='Informações sobre Patrono'),
        ),
        migrations.AlterField(
            model_name='instituicao',
            name='policia_acervo',
            field=ckeditor.fields.RichTextField(verbose_name='Políticas de Acervo'),
        ),
        migrations.AlterField(
            model_name='instituicao',
            name='sobre',
            field=ckeditor.fields.RichTextField(verbose_name='Sobre'),
        ),
        migrations.AlterField(
            model_name='instituicao',
            name='visao',
            field=ckeditor.fields.RichTextField(verbose_name='Visão'),
        ),
    ]
