# Generated by Django 3.0.5 on 2020-06-05 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instituicao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotoinstituicao',
            name='posicao',
            field=models.CharField(choices=[('R', 'Rodapé'), ('I', 'Index')], max_length=1, verbose_name='Posição'),
        ),
        migrations.AlterField(
            model_name='instituicao',
            name='email',
            field=models.CharField(max_length=100, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='instituicao',
            name='email_agendamento',
            field=models.CharField(max_length=100, verbose_name='E-mail para envio de Agendamento'),
        ),
        migrations.AlterField(
            model_name='instituicao',
            name='endereco',
            field=models.CharField(max_length=100, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='instituicao',
            name='telefone',
            field=models.CharField(max_length=100, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='membro',
            name='funcao',
            field=models.CharField(max_length=100, verbose_name='Função'),
        ),
    ]
