# Generated by Django 3.0.7 on 2020-11-26 15:15

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instituicao', '0002_auto_20201119_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='instituicao',
            name='descricao_acervo',
            field=ckeditor.fields.RichTextField(default='Novo Campo', verbose_name='Descrição do Acervo'),
            preserve_default=False,
        ),
    ]
