# Generated by Django 3.0.7 on 2020-11-19 17:12

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0003_auto_20200806_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='descricao',
            field=ckeditor.fields.RichTextField(max_length=250, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='texto',
            field=ckeditor.fields.RichTextField(verbose_name='Texto sobre evento'),
        ),
    ]
