# Generated by Django 3.0.7 on 2020-12-09 18:36

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0004_auto_20201119_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='descricao',
            field=ckeditor.fields.RichTextField(max_length=450, verbose_name='Descrição'),
        ),
    ]
