# Generated by Django 3.1.4 on 2020-12-16 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0005_auto_20201209_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='data_fim',
            field=models.DateField(default='2020-12-01', verbose_name='Data do fim do evento'),
        ),
        migrations.AddField(
            model_name='evento',
            name='data_inicio',
            field=models.DateField(default='2020-12-01', verbose_name='Data de início do evento'),
        ),
    ]
