# Generated by Django 3.1.4 on 2020-12-16 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0006_auto_20201216_1535'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evento',
            options={'ordering': ['data_inicio'], 'verbose_name': 'Evento', 'verbose_name_plural': 'Eventos'},
        ),
        migrations.AlterField(
            model_name='evento',
            name='data_fim',
            field=models.DateField(default='1111-11-11', verbose_name='Data do fim do evento'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='data_inicio',
            field=models.DateField(default='1111-11-11', verbose_name='Data de início do evento'),
        ),
    ]
