# Generated by Django 3.0.5 on 2020-06-04 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaAcervo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Categoria')),
                ('descricao', models.TextField(verbose_name='Descrição da Categoria')),
                ('image', models.ImageField(upload_to='', verbose_name='Imagem da Categoria')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('categoria_pai', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='categorias_filhas', to='acervo.CategoriaAcervo', verbose_name='Categoria Pai')),
            ],
            options={
                'verbose_name': 'Categoria do Acervo',
                'verbose_name_plural': 'Categorias do Acervo',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='ItemAcervo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField(verbose_name='Nome')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('data', models.DateField(blank=True, null=True, verbose_name='Data do Item')),
                ('fundo', models.TextField(blank=True, null=True, verbose_name='Fundo')),
                ('id_acervo', models.IntegerField(blank=True, null=True, verbose_name='Identificador no Acervo')),
                ('url_documentacao_externa', models.TextField(blank=True, null=True, verbose_name='URL da documentação externa')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('categorias', models.ManyToManyField(to='acervo.CategoriaAcervo')),
            ],
            options={
                'verbose_name': 'Item do Acervo',
                'verbose_name_plural': 'Itens do Acervo',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='FotoItemAcervo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destaque', models.BooleanField(verbose_name='Destaque')),
                ('imagem', models.ImageField(upload_to='', verbose_name='Imagem do Item do Acervo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('item_acervo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fotos', to='acervo.ItemAcervo', verbose_name='Item do Acervo')),
            ],
            options={
                'verbose_name': 'Foto do Item do Acervo',
                'verbose_name_plural': 'Fotos dos Itens do Acervo',
                'ordering': ['criado_em'],
            },
        ),
    ]
