# Generated by Django 3.0.7 on 2020-07-08 15:08

from django.db import migrations
from django.contrib.postgres.operations import UnaccentExtension


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        UnaccentExtension()
    ]
