# Generated by Django 3.0.5 on 2020-06-05 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acervo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemacervo',
            name='fundo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Fundo'),
        ),
        migrations.AlterField(
            model_name='itemacervo',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='itemacervo',
            name='url_documentacao_externa',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='URL da documentação externa'),
        ),
    ]
