# Generated by Django 3.0.7 on 2020-06-16 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acervo', '0002_auto_20200605_1038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemacervo',
            name='url_documentacao_externa',
        ),
    ]
