# Generated by Django 3.0.7 on 2020-11-19 17:12

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acervo', '0002_categoriaacervo_fotoitemacervo_itemacervo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dimensao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100, verbose_name='Tipo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Dimensão',
                'verbose_name_plural': 'Dimensões',
                'ordering': ['criado_em'],
            },
        ),
        migrations.AlterField(
            model_name='categoriaacervo',
            name='descricao',
            field=ckeditor.fields.RichTextField(verbose_name='Descrição da Categoria'),
        ),
        migrations.AlterField(
            model_name='itemacervo',
            name='descricao',
            field=ckeditor.fields.RichTextField(verbose_name='Descrição'),
        ),
        migrations.CreateModel(
            name='DimensaoItemAcervo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.CharField(max_length=50, verbose_name='Quantidade')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('dimensao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dimensoes', to='acervo.Dimensao', verbose_name='Dimensão')),
                ('item_acervo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='item_acervo', to='acervo.ItemAcervo', verbose_name='Item do Acervo')),
            ],
            options={
                'verbose_name': 'Dimensão do Item',
                'verbose_name_plural': 'Dimensões do Item',
                'ordering': ['criado_em'],
            },
        ),
    ]
