# Generated by Django 3.0.7 on 2020-06-18 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acervo', '0003_remove_itemacervo_url_documentacao_externa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoriaacervo',
            old_name='image',
            new_name='imagem',
        ),
    ]
