# Generated by Django 3.0.7 on 2020-11-25 15:08

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acervo', '0005_atividadeevento_autor_editora_formadocumento_idioma_periodicidade_problemaconservacao_produtorinstit'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividadeevento',
            name='data_fim',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Fim do Evento'),
        ),
        migrations.AddField(
            model_name='atividadeevento',
            name='data_inicio',
            field=models.DateField(default='2020-11-25', verbose_name='Data de Início do Evento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='atividadeevento',
            name='especificação',
            field=ckeditor.fields.RichTextField(default='teste', verbose_name='Especificação da Atividade/Evento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='atividadeevento',
            name='local',
            field=models.CharField(default='teste', max_length=100, verbose_name='Local do Evento'),
            preserve_default=False,
        ),
    ]
