# Generated by Django 3.0.7 on 2020-11-26 15:15

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acervo', '0007_auto_20201125_1246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoriaacervo',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='itemacervo',
            name='data',
        ),
        migrations.RemoveField(
            model_name='itemacervo',
            name='descricao',
        ),
        migrations.AddField(
            model_name='categoriaacervo',
            name='descricao_curta',
            field=models.TextField(default='Novo Campo', verbose_name='Descrição Curta da Categoria'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='categoriaacervo',
            name='descricao_longa',
            field=ckeditor.fields.RichTextField(default='Novo Campo', verbose_name='Descrição Longa da Categoria'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itemacervo',
            name='data_fim',
            field=models.DateField(blank=True, null=True, verbose_name='Data do Fim da Produção do Item'),
        ),
        migrations.AddField(
            model_name='itemacervo',
            name='data_inicio',
            field=models.DateField(default='2020-11-26', verbose_name='Data de Produção do Item'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itemacervo',
            name='descricao_curta',
            field=models.TextField(default='Novo Campo', verbose_name='Descrição Curta'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itemacervo',
            name='descricao_longa',
            field=ckeditor.fields.RichTextField(default='Novo Campo', verbose_name='Descrição Longa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itemacervo',
            name='local',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Local de Produção'),
        ),
        migrations.AddField(
            model_name='itemacervo',
            name='origem',
            field=ckeditor.fields.RichTextField(default='Novo Campo', verbose_name='Origem'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itemacervo',
            name='tipo_documento',
            field=models.CharField(default='Novo Campo', max_length=100, verbose_name='Tipo de Documento'),
            preserve_default=False,
        ),
    ]
