# Generated by Django 3.0.7 on 2020-11-27 15:43

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acervo', '0008_auto_20201126_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemacervo',
            name='acesso',
            field=models.CharField(choices=[('1', 'Livre'), ('2', 'Restrito')], default='1', max_length=2, verbose_name='Acesso'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itemacervo',
            name='classificacao',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Classificação'),
        ),
        migrations.AddField(
            model_name='itemacervo',
            name='cromia',
            field=models.CharField(blank=True, choices=[('1', 'Branco & Preto'), ('2', 'Cores')], max_length=2, null=True, verbose_name='Cromia'),
        ),
        migrations.AddField(
            model_name='itemacervo',
            name='descritores',
            field=models.TextField(default='Novo campo', help_text='Separar cada descritor usando ";"', verbose_name='Descritores'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itemacervo',
            name='exemplares',
            field=models.IntegerField(default=1, verbose_name='Quantidade de Exemplares'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itemacervo',
            name='itens',
            field=models.IntegerField(default=1, verbose_name='Quantidade de itens'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itemacervo',
            name='local_custodia',
            field=models.TextField(default='Novo campo', verbose_name='Local de Custódia'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itemacervo',
            name='observacoes',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Observações'),
        ),
        migrations.AddField(
            model_name='itemacervo',
            name='referencia',
            field=ckeditor.fields.RichTextField(default='Novo Campo', verbose_name='Referência'),
            preserve_default=False,
        ),
    ]
