# Generated by Django 3.0.7 on 2020-11-30 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acervo', '0009_auto_20201127_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemacervo',
            name='abordagem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='itens', to='acervo.Abordagem', verbose_name='Abordagem'),
        ),
        migrations.AddField(
            model_name='itemacervo',
            name='atividades_eventos',
            field=models.ManyToManyField(blank=True, related_name='itens', to='acervo.AtividadeEvento', verbose_name='Atividade/Evento'),
        ),
        migrations.AddField(
            model_name='itemacervo',
            name='editora',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='itens', to='acervo.Editora', verbose_name='Editora'),
        ),
        migrations.AddField(
            model_name='itemacervo',
            name='forma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='itens', to='acervo.FormaDocumento', verbose_name='Forma do Documento'),
        ),
        migrations.AddField(
            model_name='itemacervo',
            name='formato',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='itens', to='acervo.TipoFormato', verbose_name='Formato'),
        ),
        migrations.AddField(
            model_name='itemacervo',
            name='fundo_colecao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='itens', to='acervo.FundoColecao', verbose_name='Fundo/Coleção'),
        ),
        migrations.AddField(
            model_name='itemacervo',
            name='idiomas',
            field=models.ManyToManyField(blank=True, related_name='itens', to='acervo.Idioma', verbose_name='Idioma'),
        ),
        migrations.AddField(
            model_name='itemacervo',
            name='periodicidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='itens', to='acervo.Periodicidade', verbose_name='Periodicidade'),
        ),
        migrations.AddField(
            model_name='itemacervo',
            name='problemas_conservacao',
            field=models.ManyToManyField(blank=True, related_name='itens', to='acervo.ProblemaConservacao', verbose_name='Problema de Conservação'),
        ),
        migrations.AddField(
            model_name='itemacervo',
            name='produtor_instituicao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='itens', to='acervo.ProdutorInstituicao', verbose_name='Produtor/Instituição'),
        ),
        migrations.AddField(
            model_name='itemacervo',
            name='reproducao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='itens', to='acervo.TipoReproducao', verbose_name='Reprodução'),
        ),
        migrations.AddField(
            model_name='itemacervo',
            name='suporte',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='itens', to='acervo.TipoSuporte', verbose_name='Suporte'),
        ),
        migrations.AddField(
            model_name='itemacervo',
            name='tecnica_registro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='itens', to='acervo.TecnicaRegistro', verbose_name='Técnica de Registro'),
        ),
    ]
