# Generated by Django 3.0.7 on 2020-12-01 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acervo', '0011_remove_itemacervo_fundo'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemacervo',
            name='autores',
            field=models.ManyToManyField(blank=True, related_name='itens', to='acervo.Autor', verbose_name='Autores'),
        ),
    ]
