# Generated by Django 3.0.7 on 2020-12-01 16:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acervo', '0012_itemacervo_autores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemacervo',
            name='exemplares',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quantidade de Exemplares'),
        ),
        migrations.AlterField(
            model_name='itemacervo',
            name='itens',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantidade de itens'),
        ),
    ]
