# Generated by Django 3.0.7 on 2020-12-03 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acervo', '0013_auto_20201201_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtorinstituicao',
            name='fundo_colecao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='produtores', to='acervo.FundoColecao', verbose_name='Fundo/Coleção'),
        ),
        migrations.AddField(
            model_name='produtorinstituicao',
            name='sigla',
            field=models.CharField(default='SP', max_length=5, verbose_name='Nome do Produtor/Instituição'),
            preserve_default=False,
        ),
    ]
