# Generated by Django 3.0.7 on 2020-12-07 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acervo', '0015_itemacervo_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemacervo',
            name='data_fim_formato',
            field=models.CharField(blank=True, choices=[('C', 'Data completa'), ('MA', 'Mês/Ano'), ('A', 'Apenas ano')], max_length=2, null=True, verbose_name='Formato da Data Final'),
        ),
        migrations.AddField(
            model_name='itemacervo',
            name='data_inicio_formato',
            field=models.CharField(choices=[('C', 'Data completa'), ('MA', 'Mês/Ano'), ('A', 'Apenas ano')], default='C', max_length=2, verbose_name='Formato da Data Inicial'),
            preserve_default=False,
        ),
    ]
