# Generated by Django 3.0.7 on 2020-12-15 16:58

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acervo', '0016_auto_20201207_1526'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100, verbose_name='Tipo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Tipo de Documento',
                'verbose_name_plural': 'Tipo de Documento',
                'ordering': ['criado_em'],
            },
        ),
        migrations.AlterModelOptions(
            name='itemacervo',
            options={'ordering': ['titulo'], 'verbose_name': 'Item do Acervo', 'verbose_name_plural': 'Itens do Acervo'},
        ),
        migrations.RemoveField(
            model_name='itemacervo',
            name='id_acervo',
        ),
        migrations.RemoveField(
            model_name='itemacervo',
            name='nome',
        ),
        migrations.AddField(
            model_name='itemacervo',
            name='notacao',
            field=models.IntegerField(blank=True, null=True, verbose_name='Notação'),
        ),
        migrations.AlterField(
            model_name='itemacervo',
            name='referencia',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Referência'),
        ),
        migrations.AlterField(
            model_name='itemacervo',
            name='titulo',
            field=models.CharField(help_text='Não utilizar o caractere "/".', max_length=100, verbose_name='Título do item'),
        ),
        migrations.AlterField(
            model_name='produtorinstituicao',
            name='sigla',
            field=models.CharField(max_length=5, verbose_name='Sigla do Produtor/Instituição'),
        ),
        migrations.AlterField(
            model_name='itemacervo',
            name='tipo_documento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='itens', to='acervo.TipoDocumento', verbose_name='Tipo de Documento'),
        ),
    ]
