# Generated by Django 3.0.5 on 2020-06-04 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diretor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField(verbose_name='Nome')),
                ('sobre', models.TextField(verbose_name='Sobre')),
                ('inicio_direcao', models.DateField(verbose_name='Início da direçao')),
                ('fim_direcao', models.DateField(verbose_name='Fim da direção')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Diretor',
                'verbose_name_plural': 'Diretores',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='FotoDiretor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destaque', models.BooleanField(verbose_name='Destaque')),
                ('imagem', models.ImageField(upload_to='', verbose_name='Imagem do Diretor')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('diretor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fotos', to='galeria_diretores.Diretor', verbose_name='Diretor')),
            ],
            options={
                'verbose_name': 'Foto do Diretor',
                'verbose_name_plural': 'Fotos dos Diretores',
                'ordering': ['criado_em'],
            },
        ),
    ]
