# Generated by Django 3.1.4 on 2020-12-14 21:04

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Galeria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Galeria')),
                ('descricao', ckeditor.fields.RichTextField(verbose_name='Descrição da Galeria')),
                ('imagem', models.ImageField(upload_to='', verbose_name='Imagem da Galeria')),
                ('ativo', models.BooleanField(help_text='Este campo indica se este registro já está pronto para aparecer no site publicamente', verbose_name='Registro ativo?')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Galeria',
                'verbose_name_plural': 'Galerias',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Personalidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('funcao', models.CharField(blank=True, max_length=100, null=True, verbose_name='Função')),
                ('sobre', ckeditor.fields.RichTextField(verbose_name='Sobre')),
                ('inicio_servico', models.DateField(verbose_name='Início dos serviços prestados')),
                ('fim_servico', models.DateField(verbose_name='Fim dos serviços prestados')),
                ('ativo', models.BooleanField(help_text='Este campo indica se este registro já está pronto para aparecer no site publicamente', verbose_name='Registro ativo?')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('galerias', models.ManyToManyField(related_name='galerias', to='galeria_diretores.Galeria')),
            ],
            options={
                'verbose_name': 'Personalidade',
                'verbose_name_plural': 'Personalidades',
                'ordering': ['inicio_servico'],
            },
        ),
        migrations.CreateModel(
            name='FotoPersonalidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destaque', models.BooleanField(verbose_name='Destaque')),
                ('imagem', models.ImageField(upload_to='', verbose_name='Imagem da Personalidade')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('personalidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='personalidade', to='galeria_diretores.personalidade', verbose_name='Personalidade')),
            ],
            options={
                'verbose_name': 'Foto da Personalidade',
                'verbose_name_plural': 'Fotos das Personalidades',
                'ordering': ['criado_em'],
            },
        ),
    ]
