# Generated by Django 3.0.7 on 2020-06-16 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('galeria_diretores', '0002_auto_20200605_1038'),
    ]

    operations = [
        migrations.CreateModel(
            name='FotoPersonalidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destaque', models.BooleanField(verbose_name='Destaque')),
                ('imagem', models.ImageField(upload_to='', verbose_name='Imagem da Personalidade')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Foto da Personalidade',
                'verbose_name_plural': 'Fotos das Personalidades',
                'ordering': ['criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Galeria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Galeria')),
                ('descricao', models.TextField(verbose_name='Descrição da Galeria')),
                ('image', models.ImageField(upload_to='', verbose_name='Imagem da Galeria')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Galeria',
                'verbose_name_plural': 'Galerias',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Personalidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('funcao', models.CharField(blank=True, max_length=100, null=True, verbose_name='Função')),
                ('sobre', models.TextField(verbose_name='Sobre')),
                ('inicio_servico', models.DateField(verbose_name='Início dos serviços prestados')),
                ('fim_servico', models.DateField(verbose_name='Fim dos serviços prestados')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('galerias', models.ManyToManyField(to='galeria_diretores.Galeria')),
            ],
            options={
                'verbose_name': 'Personalidade',
                'verbose_name_plural': 'Personalidades',
                'ordering': ['nome'],
            },
        ),
        migrations.RemoveField(
            model_name='fotodiretor',
            name='diretor',
        ),
        migrations.DeleteModel(
            name='Diretor',
        ),
        migrations.DeleteModel(
            name='FotoDiretor',
        ),
        migrations.AddField(
            model_name='fotopersonalidade',
            name='personalidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fotos', to='galeria_diretores.Personalidade', verbose_name='Personalidade'),
        ),
    ]
