# Generated by Django 3.0.7 on 2020-06-16 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GrupoPesquisa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Grupo')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição do Grupo')),
                ('texto_livre', models.TextField(verbose_name='Texto Livre')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Grupo de Pesquisa',
                'verbose_name_plural': 'Grupos de Pesquisa',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Membro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('funcao', models.CharField(blank=True, max_length=100, null=True, verbose_name='Função')),
                ('descricao', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descrição do Trabalho do Membro')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Foto do Membro do Grupo de Pesquisa')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('grupo_pesquisa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='membros', to='pesquisas.GrupoPesquisa', verbose_name='Grupo de Pesquisa')),
            ],
            options={
                'verbose_name': 'Membro do Grupo de Pesquisa',
                'verbose_name_plural': 'Membros do Grupo de Pesquisa',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='FotoGrupoPesquisa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destaque', models.BooleanField(verbose_name='Destaque')),
                ('imagem', models.ImageField(upload_to='', verbose_name='Imagem do Grupo de Pesquisa')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('grupo_pesquisa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fotos', to='pesquisas.GrupoPesquisa', verbose_name='Grupo de Pesquisa')),
            ],
            options={
                'verbose_name': 'Foto do Grupo de Pesquisa',
                'verbose_name_plural': 'Fotos dos Grupos de Pesquisa',
                'ordering': ['criado_em'],
            },
        ),
    ]
