# Generated by Django 3.0.7 on 2020-12-09 18:36

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('linha_tempo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='acontecimento',
            options={'ordering': ['data'], 'verbose_name': 'Acontecimento da Linha do Tempo', 'verbose_name_plural': 'Acontecimentos da Linha do Tempo'},
        ),
        migrations.AlterModelOptions(
            name='fotoacontecimento',
            options={'ordering': ['nome'], 'verbose_name': 'Foto do Acontecimento', 'verbose_name_plural': 'Fotos dos Acontecimentos'},
        ),
        migrations.AlterField(
            model_name='acontecimento',
            name='descricao',
            field=ckeditor.fields.RichTextField(max_length=500, verbose_name='Descrição '),
        ),
        migrations.AlterField(
            model_name='linhadotempo',
            name='descricao',
            field=ckeditor.fields.RichTextField(max_length=500, verbose_name='Descrição curta'),
        ),
    ]
