# Generated by Django 3.0.5 on 2020-06-05 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linha_tempo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='titulo',
            field=models.CharField(max_length=255, verbose_name='Título'),
        ),
    ]
