# Generated by Django 3.0.7 on 2020-12-09 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('linha_tempo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fotoacontecimento',
            options={'ordering': ['nome'], 'verbose_name': 'Foto do Acontecimento', 'verbose_name_plural': 'Fotos dos Acontecimentos'},
        ),
    ]
