# Generated by Django 3.0.7 on 2020-12-10 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('linha_tempo', '0002_auto_20201209_1536'),
        ('linha_tempo', '0002_auto_20201209_1316'),
    ]

    operations = [
    ]
