# Generated by Django 3.1.4 on 2020-12-15 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linha_tempo', '0003_merge_20201210_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linhadotempo',
            name='fim_periodo',
            field=models.DateField(blank=True, null=True, verbose_name='Fim dessa linha do tempo'),
        ),
    ]
