# Generated by Django 3.0.5 on 2020-06-04 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.TextField(verbose_name='Título')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('corpo', models.TextField(verbose_name='Corpo da Notícia')),
                ('destaque', models.BooleanField(verbose_name='Destaque')),
                ('periodo_destaque', models.IntegerField(verbose_name='Tempo em Destaque')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Notícia',
                'verbose_name_plural': 'Notícias',
                'ordering': ['titulo'],
            },
        ),
        migrations.CreateModel(
            name='FotoNoticia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destaque', models.BooleanField(verbose_name='Destaque')),
                ('imagem', models.ImageField(upload_to='', verbose_name='Imagem da Notícia')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('noticia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fotos', to='noticias.Noticia', verbose_name='Notícia')),
            ],
            options={
                'verbose_name': 'Foto da Notícia',
                'verbose_name_plural': 'Fotos das Notícias',
                'ordering': ['criado_em'],
            },
        ),
    ]
