# Generated by Django 3.0.5 on 2020-06-05 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='descricao',
            field=models.TextField(max_length=250, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='periodo_destaque',
            field=models.IntegerField(blank=True, null=True, verbose_name='Tempo em Destaque'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='titulo',
            field=models.CharField(max_length=100, verbose_name='Título'),
        ),
    ]
